### ISSUE TITLE
Movement, Speed Change & Graphical Glitches. [1.6.0 Patched]

### ISSUE THREAD

**Issue by Tomahawk1o1** [X-Niter/eol-tbd#9]

**Comment by Tomahawk1o1** [comment]
For some reason I can't update the OP so:

While walking, direction and speed seem to change at random. I've also recently started seeing texture glitches. I'm providing a video and log files. Please let me know if there's any other info I can share or collect to help with this. 

https://www.youtube.com/watch?v=84lyQ1VM4nk

One recent change I made was to use Adoptium: https://adoptium.net/temurin/releases/?version=8

These issues were present before this change. Including some older logs as well. 

Newest - https://pastebin.com/93R27GmR
 - https://pastebin.com/ib8wE2GP

Pre Adoptium - https://pastebin.com/ztKtyDDp

**Comment by Tomahawk1o1** [comment]
![EOLTBD](https://user-images.githubusercontent.com/82111451/186977899-f2748174-1cd3-4db2-b0be-2d5bc955989f.png)

also now getting spammed with PvP warnings at spawn, back on regular ole java logs below. 

https://mclo.gs/fBbujKy

**Comment by X-Niter** [comment]
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 47, Size: 47
```
^ @Tomahawk1o1  This is an issue with an IE Addon mod, KnoxHack actually found there is already a commit to fix the issue on the mod, hopefully I can push for them to get the fix uploaded for EOL 1.6.0.

The other issues I saw in the video, are not caught by the log but the speed and video texture glitches, this one is a multiplayer only issue that looks to come from client side optimization mods (Not that it's one mod specifically but a combination of a few). 
I'll do what I can with testing for these issue on 1.6.0, however, due to the massive update that 1.6.0 brings, I am very confident the majority of the issues in the video will clear up.

I'll be leaving this open untill after 1.6.0 release and fully confirming if it is fixed or not on the server side.

**Comment by Tomahawk1o1** [comment]
Thanks for a quick update! What mods can I mess around with removing? I'd guess FoamFix/BetterFPS?

**Comment by X-Niter** [comment]
@Tomahawk1o1 , Remove Vanilla Fix, use CensoredASM, add Surge, keep foam fix and keep better fps. 

The bounds crash is an actual mod specific issue being looked into to try and get the devs to push the update.

Other then that, this is all I can say for right now as a conjuction of issues have been fixed by 1.6.0 that hugley came down to "None client side only mods". 
A good part of it was also my DTMI mod that fixed a whole lot about 7DTM mod that cleared up multiple issues as well. 


So you can definilty try the above stated, but a lot of things are just down deep inside the actual content mods that are clashing together accidently.

**Comment by Tomahawk1o1** [comment]
It did not like that: https://mclo.gs/aj2j0uw 

Edit: Probably just an issue with me trying to use two versions of Surge at once, as a slightly older version was already included in the pack. Please disregard.

**Comment by Tomahawk1o1** [comment]
I hope this leads to something helpful, I still get plenty of crash warnings that don't actually seem to impact the game for a few hours of playtime at least, but the main issue is resolved. 

Changing the BetterFPS Algorithm to Riven's Half Algorithm stopped the movement changes and graphical glitches without any mod changes.
